config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registration: 'registrations' }
  root 'games#index'
  resources :games do
    resources :reviews
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :games

  validates :name, presence:true
  validates :name, length: {maximum: 20}
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  validates_presence_of :description, :creator, :title

  has_attached_file :game_img,
   styles:
   { game_index: "250x350>", game_show: "339x475>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :game_img, content_type: /\Aimage\/.*\z/

  def self.search(search)
    where("title ILIKE ? OR creator ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :rating, :user, :game, :comment

  belongs_to :game
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank? && params[:search].blank?
      @games = Game.all.order("created_at DESC")
    elsif params[:search]
      @games = Game.search(params[:search]).order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @games = Game.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @game.reviews.blank?
      @average_review = 0
    else
      @average_review = @game.reviews.average(:rating).round(2)
    end
  end

  def new
      @game = current_user.games.build
      @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
      @game = current_user.games.build(game_params)
      @game.category_id = params[:category_id]

    if @game.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    if current_user.id != @game.user_id
      redirect_to root_path
    end
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @game.category_id = params[:category_id]
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end


  private

  def game_params
    params.require(:game).permit(:title, :description, :creator, :category_id, :game_img, :rule_link)
  end

  def find_game
    @game = Game.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :find_game
  before_action :find_review, only: [:edit, :update, :destroy]



  def new
    @review = Review.new
  end

  def create

    @review = Review.new(review_params)
    @review.game_id = @game.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def edit
    if current_user.id != @review.user_id
      redirect_to root_path
    end
  end

  def update
    if @review.update(review_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_game
      @game = Game.find(params[:game_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.file_field :game_img %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  <%= f.input :title, label: "Game Title" %>
  <%= f.input :description %>
  <%= f.input :creator %>
  <%= f.input :rule_link %>
  <%= f.button :submit %>
<% end %>

app/views/games/_video.html.erb
<div class="bs-example">
    <!-- Button HTML (to Trigger Modal) -->
    <a href="#myModal" class="btn btn-custom2" data-toggle="modal">Watch Rules Video</a>

    <!-- Modal HTML -->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><%= @game.title %> Rules</h4>
                </div>
                <div class="modal-body">
                    <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" id="cartoonVideo" src="<%= @game.rule_link %>" frameborder="0" allowfullscreen></iframe>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/games/edit.html.erb
<h1>Edit Tabletop Game</h1>

<%= simple_form_for @game, html: {multipart: true} do |f| %>
  <%= f.file_field :game_img %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title, label: "Game Title" %>
  <%= f.input :description %>
  <%= f.input :creator %>
  <%= f.input :rule_link %>
  <%= f.button :submit %>
<% end %>

app/views/games/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @games.blank? %>
<div class="row blank">
  <h3>There are no games matching "<%= params[:search] %>".</h3>
</div>
<% else %>
<div class="container-fluid">
  <% @games.each do |game| %>
    <div class="col-md-3 col-sm-6">
      <a href="/games/ <%= game.id %>">
        <%= image_tag game.game_img.url(:game_index), class: "game" %>
      </a>
    </div>
  <% end %>
 </div>
<% end %>

app/views/games/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">

    <h1>New Tabletop Game</h1>
    <%= render 'form' %>

  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @game.game_img.url(:game_show), class: "game-show" %>
  </div>

  <div class="col-md-8">
    <div class="game-info">
      <h2 class="game-title"><%= @game.title %></h2>
      <h3 class="game-creator"><span>Designed by </span><%= @game.creator %></h3>
      <h4 class="game-creator"><%= @game.category.name %></h4>
      <h4 class="average-rating">Average Rating:</h4>
      <div class="average-review-rating" data-source=<%= @average_review %>></div>
      <span class="number-of-reviews">From <%= @game.reviews.count %> reviews </span>
      <p class="game-desc"><%= @game.description %></p>
      <%= render 'video' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1> Reviews </h1>
        <%= render @game.reviews %>
        <div>
          <%= link_to "Add Review", new_game_review_path(@game), class: "btn-custom" %>
        </div>
    </div>
  </div>
</div>



<div class="links btn-group">
  <% if user_signed_in? %>
    <% if @game.user_id == current_user.id %>
      <%= link_to "Edit", edit_game_path(@game), class: "btn btn-custom" %>
      <%= link_to "Delete", game_path(@game), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
    <% end %>
  <% end %>
</div>





<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-source');
    },
    path: '/assets/'
  });
</script>

<script type="text/javascript">
$(document).ready(function(){
    /* Get iframe src attribute value i.e. YouTube video url
    and store it in a variable */
    var url = $("#cartoonVideo").attr('src');

    /* Assign empty url value to the iframe src attribute when
    modal hide, which stop the video playing */
    $("#myModal").on('hide.bs.modal', function(){
        $("#cartoonVideo").attr('src', '');
    });

    /* Assign the initially stored url back to the iframe src
    attribute when modal is displayed again */
    $("#myModal").on('show.bs.modal', function(){
        $("#cartoonVideo").attr('src', url);
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-75674810-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-75674810-2');
</script>

    <title>Tabletop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>



    <nav class="navbar navbar-default">
      <div class="container">

        <div class="navbar-header">
<%= image_tag("rainbow", class: "nav navbar-icon navbar-brand") %>

          <%= link_to "Tabletop Reviews", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, games_path(category: category.name), class: "link" %>
                </li>
                <% end %>
                <li>
                  <%= link_to "All", root_path, class: "link" %>
                </li>
            </ul>
          </li>


          <% if user_signed_in? %>
            <li><%= link_to "Add Game", new_game_path %></li>
          <% end %>

          <li>
            <%= form_tag(games_path, method: 'get', class: 'navbar-form navbar-right') do %>
              <%= text_field_tag 'search', params[:search], class: 'form-control', placeholder: ''  %>
              <%= submit_tag "Find Game", class: 'btn btn-default', :name => nil %>
            <% end %>
          </li>
            </ul>


        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@game, @game.reviews.build]) do |f| %>
  <div id="rating-form">
    <label> Rating </label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <p> <%= review.user.username %> </p>
  <div class="review-rating" data-score="<%= review.rating %>"> </div>

  <p> <%= review.created_at.strftime("%B #{review.created_at.day.ordinalize}, %Y") %>   </p>

  <p class="review-comment"><%= review.comment %> </p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Edit", edit_game_review_path(review.game, review), class: "btn btn-custom" %>

        <%= link_to "Delete", game_review_path(review.game, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offest-1">
  <div class="edit-review-form">
    <h1> Edit Review </h1>
    <%= simple_form_for([@game, @review]) do |f| %>
      <div id="rating-form">
        <label> Rating </label>
      </div>
        <%= f.input :comment %>
        <%= f.button :submit, :class => "btn-custom2" %>
    <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1> Post Review </h1>
    <%= render 'form' %>
  </div>
</div>